/* Mock data for the admin panel — questions, users, assessments, settings */

const MODULES = [
  {
    key: "aptitude",
    label: "Aptitude Assessment",
    desc: "Quantitative, Logical, and Verbal reasoning question bank.",
    accent: "acc-green",
    color: "#1ED36A",
    icon: "Brain",
    trial: 124, main: 480,
    categories: ["Quantitative", "Logical", "Data Interpretation", "Abstract", "Verbal"],
    type: "mcq",
  },
  {
    key: "mnc",
    label: "MNC Career Prep",
    desc: "Technical MCQs focused on Data Structures, Algorithms, and Core CS.",
    accent: "acc-purple",
    color: "#8b6df0",
    icon: "Briefcase",
    trial: 96, main: 612,
    categories: ["Data Structures", "Algorithms", "System Design", "Databases", "OS", "Networking"],
    type: "mcq",
  },
  {
    key: "communication",
    label: "Communication Skills",
    desc: "Multi-skill tasks including Audio, Speaking, Reading, and Writing.",
    accent: "acc-cyan",
    color: "#06b6d4",
    icon: "MessageSquare",
    trial: 64, main: 248,
    categories: ["Audio", "Reading", "Speaking", "Writing", "Grammar"],
    type: "comm",
  },
  {
    key: "role",
    label: "Role-Based Technical",
    desc: "Context-aware conceptual and scenario-based technical evaluations.",
    accent: "acc-lime",
    color: "#84cc16",
    icon: "Target",
    trial: 88, main: 422,
    categories: ["Conceptual", "Scenario"],
    type: "mcq",
  },
  {
    key: "coding",
    label: "Coding Challenges",
    desc: "Live-judge programming problems with hidden test cases and multi-language support.",
    accent: "acc-amber",
    color: "#FFB703",
    icon: "Code",
    trial: 42, main: 186,
    categories: ["Arrays", "Strings", "Trees", "Graphs", "Dynamic Programming", "Greedy", "Math"],
    type: "coding",
    isNew: true,
  },
];

const USERS = [
  { id: "u1", name: "Aanya Sharma", email: "aanya.sharma@iitm.ac.in", role: "Student", college: "IIT Madras", status: "active", assessments: 12, lastSeen: "2 min ago", joined: "12 Mar 2026", obId: "OB-20345", avatar: "#5337BC" },
  { id: "u2", name: "Rohan Mehta", email: "rohan.m@bits-pilani.in", role: "Student", college: "BITS Pilani", status: "active", assessments: 8, lastSeen: "1 hr ago", joined: "08 Mar 2026", obId: "OB-20346", avatar: "#246CAC" },
  { id: "u3", name: "Priya Kumar", email: "priya@originbi.com", role: "Admin", college: "Origin BI", status: "active", assessments: 0, lastSeen: "now", joined: "01 Jan 2025", obId: "OB-00012", avatar: "#1ED36A" },
  { id: "u4", name: "Karan Singh", email: "karan.singh@nitt.edu", role: "Student", college: "NIT Trichy", status: "blocked", assessments: 3, lastSeen: "5 days ago", joined: "20 Feb 2026", obId: "OB-20289", avatar: "#D84C74" },
  { id: "u5", name: "Sneha Patel", email: "sneha.p@vit.ac.in", role: "Proctor", college: "VIT Vellore", status: "active", assessments: 0, lastSeen: "12 min ago", joined: "15 Feb 2026", obId: "OB-00045", avatar: "#FFB703" },
  { id: "u6", name: "Ankit Verma", email: "ankit.v@srm.ac.in", role: "Student", college: "SRM University", status: "active", assessments: 15, lastSeen: "3 hr ago", joined: "11 Feb 2026", obId: "OB-20102", avatar: "#06b6d4" },
  { id: "u7", name: "Divya Iyer", email: "divya.i@anna.edu", role: "Student", college: "Anna University", status: "pending", assessments: 0, lastSeen: "never", joined: "10 May 2026", obId: "OB-20456", avatar: "#84cc16" },
  { id: "u8", name: "Vikram Joshi", email: "v.joshi@manipal.edu", role: "Student", college: "Manipal Institute", status: "active", assessments: 6, lastSeen: "4 hr ago", joined: "28 Jan 2026", obId: "OB-19883", avatar: "#8b6df0" },
  { id: "u9", name: "Meera Nair", email: "meera@originbi.com", role: "Admin", college: "Origin BI", status: "active", assessments: 0, lastSeen: "30 min ago", joined: "12 Dec 2024", obId: "OB-00008", avatar: "#5337BC" },
  { id: "u10", name: "Hari Krishnan", email: "hari.k@psgtech.edu", role: "Student", college: "PSG Tech", status: "active", assessments: 11, lastSeen: "yesterday", joined: "05 Feb 2026", obId: "OB-20011", avatar: "#1ED36A" },
  { id: "u11", name: "Tara Reddy", email: "tara.r@iiit.ac.in", role: "Student", college: "IIIT Hyderabad", status: "active", assessments: 9, lastSeen: "55 min ago", joined: "22 Jan 2026", obId: "OB-19921", avatar: "#D84C74" },
  { id: "u12", name: "Sahil Khan", email: "sahil.k@dtu.ac.in", role: "Student", college: "Delhi Tech University", status: "blocked", assessments: 2, lastSeen: "1 week ago", joined: "15 Jan 2026", obId: "OB-19764", avatar: "#246CAC" },
];

const APTITUDE_QUESTIONS = [
  { id: "q1001", category: "Quantitative", subcategory: "Percentages", text: "If the price of a book is first decreased by 25% and then increased by 20%, the net change in price will be:", options: ["10% decrease", "5% decrease", "No change", "5% increase"], correct: 0, difficulty: "medium", marks: 2, status: "active", usage: 412 },
  { id: "q1002", category: "Logical", subcategory: "Series", text: "Find the next term: 2, 6, 12, 20, 30, ?", options: ["40", "42", "44", "46"], correct: 1, difficulty: "easy", marks: 1, status: "active", usage: 318 },
  { id: "q1003", category: "Data Interpretation", subcategory: "Bar charts", text: "Based on the chart, what was the percentage growth in Q3 over Q2?", options: ["12%", "15%", "18%", "22%"], correct: 2, difficulty: "hard", marks: 5, status: "active", usage: 64, hasImage: true },
  { id: "q1004", category: "Verbal", subcategory: "Synonyms", text: "Choose the word most similar in meaning to 'EPHEMERAL':", options: ["Lasting", "Transient", "Memorable", "Concrete"], correct: 1, difficulty: "medium", marks: 2, status: "active", usage: 256 },
  { id: "q1005", category: "Abstract", subcategory: "Pattern", text: "Which figure completes the pattern sequence shown above?", options: ["Figure A", "Figure B", "Figure C", "Figure D"], correct: 3, difficulty: "hard", marks: 5, status: "inactive", usage: 0, hasImage: true },
  { id: "q1006", category: "Quantitative", subcategory: "Ratio", text: "The ratio of present ages of A and B is 4:5. After 6 years, the ratio becomes 5:6. What is the present age of A?", options: ["18", "24", "30", "36"], correct: 1, difficulty: "medium", marks: 2, status: "active", usage: 188 },
  { id: "q1007", category: "Logical", subcategory: "Syllogism", text: "All managers are leaders. Some leaders are introverts. Which conclusion follows?", options: ["All managers are introverts", "Some managers are introverts", "No managers are introverts", "Cannot be determined"], correct: 3, difficulty: "hard", marks: 5, status: "active", usage: 91 },
];

const CODING_QUESTIONS = [
  {
    id: "c2001",
    title: "Two Sum",
    category: "Arrays",
    difficulty: "easy",
    marks: 10,
    status: "active",
    languages: ["python", "javascript", "java", "cpp"],
    timeLimit: 1000, // ms
    memoryLimit: 256, // MB
    acceptance: 78.4,
    submissions: 1240,
    testCases: 12,
    description: "Given an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to `target`. You may assume that each input would have **exactly one solution**, and you may not use the same element twice.",
    tags: ["Array", "Hash Table"],
  },
  {
    id: "c2002",
    title: "Valid Parentheses",
    category: "Strings",
    difficulty: "easy",
    marks: 10,
    status: "active",
    languages: ["python", "javascript", "java", "cpp", "go"],
    timeLimit: 1000,
    memoryLimit: 128,
    acceptance: 65.2,
    submissions: 892,
    testCases: 18,
    description: "Given a string `s` containing just the characters `'('`, `')'`, `'{'`, `'}'`, `'['` and `']'`, determine if the input string is valid.",
    tags: ["String", "Stack"],
  },
  {
    id: "c2003",
    title: "Binary Tree Level Order Traversal",
    category: "Trees",
    difficulty: "medium",
    marks: 25,
    status: "active",
    languages: ["python", "javascript", "java", "cpp"],
    timeLimit: 1500,
    memoryLimit: 256,
    acceptance: 54.8,
    submissions: 412,
    testCases: 24,
    description: "Given the root of a binary tree, return the level order traversal of its nodes' values. (i.e., from left to right, level by level).",
    tags: ["Tree", "BFS"],
  },
  {
    id: "c2004",
    title: "Longest Path in DAG",
    category: "Graphs",
    difficulty: "hard",
    marks: 50,
    status: "active",
    languages: ["python", "java", "cpp"],
    timeLimit: 3000,
    memoryLimit: 512,
    acceptance: 28.1,
    submissions: 184,
    testCases: 32,
    description: "Given a directed acyclic graph with `n` vertices, find the length of the longest path. The graph may have up to 10⁵ nodes and 2×10⁵ edges.",
    tags: ["Graph", "DP", "Topological Sort"],
  },
  {
    id: "c2005",
    title: "Climbing Stairs",
    category: "Dynamic Programming",
    difficulty: "easy",
    marks: 10,
    status: "active",
    languages: ["python", "javascript", "java"],
    timeLimit: 500,
    memoryLimit: 128,
    acceptance: 82.1,
    submissions: 1502,
    testCases: 10,
    description: "You are climbing a staircase. It takes `n` steps. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?",
    tags: ["DP", "Math"],
  },
  {
    id: "c2006",
    title: "Minimum Spanning Tree",
    category: "Graphs",
    difficulty: "hard",
    marks: 50,
    status: "inactive",
    languages: ["cpp", "java"],
    timeLimit: 2500,
    memoryLimit: 512,
    acceptance: 0,
    submissions: 0,
    testCases: 28,
    description: "Implement Kruskal's algorithm to find the minimum spanning tree of a weighted undirected graph.",
    tags: ["Graph", "MST", "Union-Find"],
    isDraft: true,
  },
];

const TEST_CASES = [
  { id: "tc1", input: "nums = [2,7,11,15]\ntarget = 9", expected: "[0,1]", visible: true, weight: 10, timeMs: 12 },
  { id: "tc2", input: "nums = [3,2,4]\ntarget = 6", expected: "[1,2]", visible: true, weight: 10, timeMs: 8 },
  { id: "tc3", input: "nums = [3,3]\ntarget = 6", expected: "[0,1]", visible: false, weight: 10, timeMs: 6 },
  { id: "tc4", input: "nums = [-1,-2,-3,-4,-5]\ntarget = -8", expected: "[2,4]", visible: false, weight: 15, timeMs: 14 },
  { id: "tc5", input: "nums = [1,5,3,8,2,4]\ntarget = 7", expected: "[2,5]", visible: false, weight: 15, timeMs: 18 },
  { id: "tc6", input: "Large input: 100000 elements", expected: "[42,99812]", visible: false, weight: 40, timeMs: 240 },
];

const ASSESSMENTS = [
  { id: "a1", name: "Campus Hire 2026 — Aptitude Round", module: "aptitude", mode: "main", status: "live", candidates: 1240, completed: 882, duration: 45, questions: 30, attempts: 1, lastUpdated: "2 hr ago" },
  { id: "a2", name: "TCS NQT Prep Mock", module: "mnc", mode: "main", status: "live", candidates: 642, completed: 412, duration: 90, questions: 60, attempts: 3, lastUpdated: "1 day ago" },
  { id: "a3", name: "SDE Coding Challenge — Round 2", module: "coding", mode: "main", status: "live", candidates: 286, completed: 184, duration: 120, questions: 4, attempts: 1, lastUpdated: "30 min ago" },
  { id: "a4", name: "Verbal Communication Trial", module: "communication", mode: "trial", status: "draft", candidates: 0, completed: 0, duration: 30, questions: 15, attempts: 999, lastUpdated: "4 days ago" },
  { id: "a5", name: "Frontend Engineer Role Fit", module: "role", mode: "main", status: "scheduled", candidates: 0, completed: 0, duration: 60, questions: 25, attempts: 1, lastUpdated: "yesterday" },
];

// Default proctoring settings shape
const DEFAULT_PROCTORING = {
  camera: { enabled: true, capture: "interval", intervalSec: 30, faceDetection: true, multiFace: "flag" },
  microphone: { enabled: false, noiseAlert: false },
  screen: { fullscreenLock: true, allowExit: 2, tabSwitchLimit: 3, screenshare: false },
  network: { ipLogging: true, vpnBlock: false, geoFence: "off" },
  identity: { idVerification: true, livenessCheck: true, photoAtStart: true },
  ai: { eyeTracking: true, suspiciousActivityAI: true, lipSync: false, plagiarismDetection: true },
  actions: { autoTerminate: false, warningCount: 3, recordSession: true, retentionDays: 90 },
};

const RECENT_ACTIVITY = [
  { user: "Aanya Sharma", action: "completed", target: "Campus Hire 2026 — Aptitude Round", time: "2 min ago", type: "success" },
  { user: "Karan Singh", action: "flagged for", target: "Multiple faces detected (Round 2)", time: "8 min ago", type: "warning" },
  { user: "Priya Kumar (Admin)", action: "edited question", target: "Two Sum (c2001)", time: "14 min ago", type: "info" },
  { user: "Rohan Mehta", action: "started", target: "TCS NQT Prep Mock", time: "21 min ago", type: "neutral" },
  { user: "Sahil Khan", action: "violation: tab switch (3/3)", target: "Aptitude Trial", time: "32 min ago", type: "danger" },
  { user: "Meera Nair (Admin)", action: "published assessment", target: "SDE Coding Challenge — Round 2", time: "1 hr ago", type: "success" },
];

Object.assign(window, {
  MODULES, USERS, APTITUDE_QUESTIONS, CODING_QUESTIONS, TEST_CASES,
  ASSESSMENTS, DEFAULT_PROCTORING, RECENT_ACTIVITY,
});
