-- ============================================================
-- Migration 003: Snapshot-Based Marks Blueprint Adaptive Engine
-- Idempotent — safe to run multiple times.
-- Adds new tables and columns needed by the v2 adaptive module.
-- ============================================================

-- ── 1. Extend block_attempts with full v2 metrics ────────────────────────────
ALTER TABLE block_attempts
  ADD COLUMN IF NOT EXISTS obtained_marks         DECIMAL(8,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_block_marks      DECIMAL(8,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS skipped_count          INT          DEFAULT 0,
  ADD COLUMN IF NOT EXISTS skipped_marks          DECIMAL(8,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS wrong_count            INT          DEFAULT 0,
  ADD COLUMN IF NOT EXISTS marks_score            DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS adaptive_accuracy      DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS attempt_accuracy       DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS skip_count_rate        DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS skipped_marks_rate     DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS skip_impact            DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS skip_confidence        DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS difficulty_handling    DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS speed_efficiency       DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS block_readiness_score  DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS snapshot_taken         BOOLEAN      DEFAULT false,
  ADD COLUMN IF NOT EXISTS metadata               JSONB        DEFAULT '{}'::jsonb;

-- ── 2. Extend adaptive_performance_analytics with v2 final report ────────────
ALTER TABLE adaptive_performance_analytics
  ADD COLUMN IF NOT EXISTS obtained_marks           DECIMAL(8,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_marks              DECIMAL(8,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS marks_percentage         DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS final_evaluation_score   DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS performance_level        VARCHAR(20)  DEFAULT 'Needs Foundation',
  ADD COLUMN IF NOT EXISTS skipped_count            INT          DEFAULT 0,
  ADD COLUMN IF NOT EXISTS skipped_marks            DECIMAL(8,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS wrong_count              INT          DEFAULT 0,
  ADD COLUMN IF NOT EXISTS skip_impact              DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS skip_confidence          DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS difficulty_handling      DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS speed_efficiency         DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS topic_mastery_score      DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reliability_score        DECIMAL(5,2) DEFAULT 100,
  ADD COLUMN IF NOT EXISTS reliability_level        VARCHAR(10)  DEFAULT 'High',
  ADD COLUMN IF NOT EXISTS topic_mastery            JSONB        DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS block_performance        JSONB        DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS category_performance     JSONB        DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS strong_topics            JSONB        DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS weak_topics              JSONB        DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS slow_topics              JSONB        DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS skipped_topics           JSONB        DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS recommended_topics       JSONB        DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS metadata                 JSONB        DEFAULT '{}'::jsonb;

-- ── 3. block_snapshots — immutable, written once on first "Next Block" ────────
-- This is the core of the snapshot-based adaptive model.
-- Once written, it is NEVER updated. Adaptive decisions use this.
CREATE TABLE IF NOT EXISTS block_snapshots (
  snapshot_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_token          VARCHAR(100) NOT NULL,
  block_number           INT          NOT NULL,
  assessment_id          BIGINT       NOT NULL REFERENCES tech_assessments(assessment_id) ON DELETE CASCADE,
  user_id                BIGINT       NOT NULL REFERENCES users(id),

  -- Snapshot of per-question answers at the moment "Next Block" was first clicked
  -- { questionId: { selectedOptionId, submittedAnswer, isCorrect, marksAwarded, timeTakenSeconds, status } }
  question_answers       JSONB        NOT NULL DEFAULT '{}'::jsonb,

  -- Aggregate metrics computed from snapshot answers
  total_questions        INT          DEFAULT 0,
  correct_count          INT          DEFAULT 0,
  wrong_count            INT          DEFAULT 0,
  skipped_count          INT          DEFAULT 0,
  attempted_count        INT          DEFAULT 0,
  total_block_marks      DECIMAL(8,2) DEFAULT 0,
  obtained_marks         DECIMAL(8,2) DEFAULT 0,
  skipped_marks          DECIMAL(8,2) DEFAULT 0,
  marks_score            DECIMAL(5,2) DEFAULT 0,
  adaptive_accuracy      DECIMAL(5,2) DEFAULT 0,
  attempt_accuracy       DECIMAL(5,2) DEFAULT 0,
  skip_count_rate        DECIMAL(5,2) DEFAULT 0,
  skipped_marks_rate     DECIMAL(5,2) DEFAULT 0,
  skip_impact            DECIMAL(5,2) DEFAULT 0,
  skip_confidence        DECIMAL(5,2) DEFAULT 0,
  difficulty_handling    DECIMAL(5,2) DEFAULT 0,
  speed_efficiency       DECIMAL(5,2) DEFAULT 0,
  block_readiness_score  DECIMAL(5,2) DEFAULT 0,
  next_block_difficulty  VARCHAR(10)  DEFAULT 'easy'
    CHECK (next_block_difficulty IN ('easy','medium','hard')),
  time_taken_seconds     INT          DEFAULT 0,

  -- Blueprint slot coverage for this block (which subcategories were used)
  coverage_map           JSONB        DEFAULT '{}'::jsonb,

  created_at             TIMESTAMP    NOT NULL DEFAULT NOW(),

  UNIQUE (attempt_token, block_number)
);

-- ── 4. adaptive_question_timing — per-question time tracking ─────────────────
-- Stores time spent on each question within a block attempt.
CREATE TABLE IF NOT EXISTS adaptive_question_timing (
  timing_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_token          VARCHAR(100) NOT NULL,
  block_number           INT          NOT NULL,
  question_id            BIGINT       NOT NULL,
  time_started           TIMESTAMP    NULL,
  time_ended             TIMESTAMP    NULL,
  time_taken_seconds     INT          DEFAULT 0,
  expected_time_seconds  INT          DEFAULT 0,
  speed_score            DECIMAL(5,2) DEFAULT 0,
  review_count           INT          DEFAULT 0,   -- how many times user revisited
  created_at             TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMP    NOT NULL DEFAULT NOW(),
  UNIQUE (attempt_token, block_number, question_id)
);

-- ── 5. adaptive_blueprint — marks blueprint per assessment ───────────────────
-- Stores the marks blueprint created when admin sets up an adaptive assessment.
CREATE TABLE IF NOT EXISTS adaptive_blueprint (
  blueprint_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id          BIGINT       NOT NULL REFERENCES tech_assessments(assessment_id) ON DELETE CASCADE,
  total_marks            DECIMAL(8,2) NOT NULL DEFAULT 100,
  total_blocks           INT          NOT NULL DEFAULT 4,
  marks_per_block        DECIMAL(8,2) NOT NULL DEFAULT 25,
  seconds_per_mark       INT          NOT NULL DEFAULT 45,

  -- Category weightage: { "Quantitative Aptitude": { weightPct: 30, targetMarks: 30 }, ... }
  category_blueprint     JSONB        NOT NULL DEFAULT '{}'::jsonb,

  -- Subcategory blueprint: { "Quantitative Aptitude": { "Number System": { targetMarks: 5 }, ... } }
  subcategory_blueprint  JSONB        NOT NULL DEFAULT '{}'::jsonb,

  -- Difficulty profiles: { easy: {easy:70,medium:30,hard:0}, medium: {...}, hard: {...} }
  difficulty_profiles    JSONB        NOT NULL DEFAULT '{
    "easy":   {"easy":70,"medium":30,"hard":0},
    "medium": {"easy":20,"medium":60,"hard":20},
    "hard":   {"easy":0,"medium":30,"hard":70}
  }'::jsonb,

  created_at             TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMP    NOT NULL DEFAULT NOW(),
  UNIQUE (assessment_id)
);

-- ── 6. adaptive_subcategory_coverage — tracks subcategory rotation ───────────
-- Updated after each block is generated so the next block can rotate topics.
CREATE TABLE IF NOT EXISTS adaptive_subcategory_coverage (
  coverage_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_token          VARCHAR(100) NOT NULL,
  assessment_id          BIGINT       NOT NULL REFERENCES tech_assessments(assessment_id) ON DELETE CASCADE,
  -- { "Quantitative Aptitude": { "Number System": { marksUsed: 5, questionsUsed: 2 }, ... } }
  coverage               JSONB        NOT NULL DEFAULT '{}'::jsonb,
  created_at             TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMP    NOT NULL DEFAULT NOW(),
  UNIQUE (attempt_token)
);

-- ── 7. Extend tech_aptitude_attempt_questions with per-question timing ────────
ALTER TABLE tech_aptitude_attempt_questions
  ADD COLUMN IF NOT EXISTS time_taken_seconds   INT     DEFAULT 0,
  ADD COLUMN IF NOT EXISTS expected_time_seconds INT    DEFAULT 0,
  ADD COLUMN IF NOT EXISTS speed_score          DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_skipped           BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_locked            BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS display_order        INT     DEFAULT 0;

-- ── 8. Indexes ────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_block_snapshots_token        ON block_snapshots(attempt_token);
CREATE INDEX IF NOT EXISTS idx_block_snapshots_block        ON block_snapshots(attempt_token, block_number);
CREATE INDEX IF NOT EXISTS idx_block_snapshots_assessment   ON block_snapshots(assessment_id);
CREATE INDEX IF NOT EXISTS idx_question_timing_token        ON adaptive_question_timing(attempt_token);
CREATE INDEX IF NOT EXISTS idx_question_timing_block        ON adaptive_question_timing(attempt_token, block_number);
CREATE INDEX IF NOT EXISTS idx_adaptive_blueprint_assess    ON adaptive_blueprint(assessment_id);
CREATE INDEX IF NOT EXISTS idx_subcategory_coverage_token   ON adaptive_subcategory_coverage(attempt_token);

-- ── 9. Triggers ───────────────────────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_question_timing_updated_at') THEN
    CREATE TRIGGER trg_question_timing_updated_at
      BEFORE UPDATE ON adaptive_question_timing FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_adaptive_blueprint_updated_at') THEN
    CREATE TRIGGER trg_adaptive_blueprint_updated_at
      BEFORE UPDATE ON adaptive_blueprint FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_subcategory_coverage_updated_at') THEN
    CREATE TRIGGER trg_subcategory_coverage_updated_at
      BEFORE UPDATE ON adaptive_subcategory_coverage FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
END $$;

-- ── Verification ──────────────────────────────────────────────────────────────
-- SELECT table_name FROM information_schema.tables
-- WHERE table_schema='public'
--   AND table_name IN (
--     'block_snapshots','adaptive_question_timing',
--     'adaptive_blueprint','adaptive_subcategory_coverage'
--   );
