-- Block-Based Adaptive Assessment System Schema
-- Additions to existing tech assessment schema

-- Add block configuration to assessments
ALTER TABLE tech_assessments 
ADD COLUMN IF NOT EXISTS block_config JSONB DEFAULT '{"enabled": false, "blocks_per_assessment": 4, "questions_per_block": 5}'::jsonb,
ADD COLUMN IF NOT EXISTS adaptive_config JSONB DEFAULT '{"enabled": false, "difficulty_progression": "static", "adaptation_strategy": "performance_based"}'::jsonb,
ADD COLUMN IF NOT EXISTS categories JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS difficulty_marks JSONB DEFAULT '{"easy": 1, "medium": 2, "hard": 5}'::jsonb,
ADD COLUMN IF NOT EXISTS difficulty_negative_marks JSONB DEFAULT '{"easy": 0, "medium": 0.25, "hard": 0.25}'::jsonb,
ADD COLUMN IF NOT EXISTS question_limit INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS trial_question_limit INT DEFAULT 5,
ADD COLUMN IF NOT EXISTS tab_switch_limit INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS anti_copy_enabled BOOLEAN DEFAULT FALSE;

-- Add block tracking to aptitude attempt questions
ALTER TABLE tech_aptitude_attempt_questions
    ADD COLUMN IF NOT EXISTS block_number INT,
    ADD COLUMN IF NOT EXISTS block_sequence_order INT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_apt_attempt_questions_block_order
    ON tech_aptitude_attempt_questions(aptitude_attempt_id, block_number, block_sequence_order);

CREATE INDEX IF NOT EXISTS idx_apt_attempt_questions_block
    ON tech_aptitude_attempt_questions(aptitude_attempt_id, block_number);

-- Block metadata table for tracking block-level information
CREATE TABLE IF NOT EXISTS adaptive_blocks (
    block_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES tech_assessments(assessment_id) ON DELETE CASCADE,
    block_number INT NOT NULL,
    difficulty_distribution JSONB NOT NULL DEFAULT '{"easy": 60, "medium": 30, "hard": 10}'::jsonb,
    category_weights JSONB DEFAULT '{}'::jsonb,
    time_limit_minutes INT DEFAULT NULL,
    is_adaptive BOOLEAN NOT NULL DEFAULT false,
    adaptation_triggers JSONB DEFAULT '{"accuracy_threshold": 0.8, "time_threshold": 0.7}'::jsonb,
    generated_questions JSONB DEFAULT '[]'::jsonb,
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'generated', 'completed', 'locked')),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (assessment_id, block_number)
);

-- Block attempts table to track user progress through blocks
CREATE TABLE IF NOT EXISTS block_attempts (
    block_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_token VARCHAR(100) NOT NULL,
    block_id BIGINT NOT NULL REFERENCES adaptive_blocks(block_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    block_number INT NOT NULL,
    status VARCHAR(20) DEFAULT 'not_started' CHECK (status IN ('not_started', 'in_progress', 'completed', 'locked')),
    started_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    time_taken_seconds INT DEFAULT 0,
    accuracy_score DECIMAL(5,4) DEFAULT 0.0000,
    difficulty_achieved VARCHAR(10) DEFAULT 'easy' CHECK (difficulty_achieved IN ('easy', 'medium', 'hard')),
    next_block_difficulty VARCHAR(10) DEFAULT 'medium' CHECK (next_block_difficulty IN ('easy', 'medium', 'hard')),
    performance_metrics JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (attempt_token, block_number)
);

-- Adaptive paths table to track different learning paths
CREATE TABLE IF NOT EXISTS adaptive_paths (
    path_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES tech_assessments(assessment_id) ON DELETE CASCADE,
    path_name VARCHAR(100) NOT NULL,
    path_description TEXT,
    difficulty_progression JSONB NOT NULL DEFAULT '["easy", "medium", "hard"]'::jsonb,
    category_specialization JSONB DEFAULT '{}'::jsonb,
    time_adaptation_factor DECIMAL(3,2) DEFAULT 1.0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Question pool metadata for adaptive selection
CREATE TABLE IF NOT EXISTS question_pool_metadata (
    pool_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES tech_assessments(assessment_id) ON DELETE CASCADE,
    category VARCHAR(100) NOT NULL,
    difficulty VARCHAR(10) NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')),
    total_questions INT NOT NULL DEFAULT 0,
    available_questions INT NOT NULL DEFAULT 0,
    usage_count INT NOT NULL DEFAULT 0,
    last_used TIMESTAMP NULL,
    pool_efficiency DECIMAL(5,4) DEFAULT 1.0000,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (assessment_id, category, difficulty)
);

-- Block generation cache for performance optimization
CREATE TABLE IF NOT EXISTS block_generation_cache (
    cache_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES tech_assessments(assessment_id) ON DELETE CASCADE,
    block_number INT NOT NULL,
    difficulty_profile JSONB NOT NULL,
    category_profile JSONB DEFAULT '{}'::jsonb,
    generated_questions JSONB NOT NULL DEFAULT '[]'::jsonb,
    cache_key VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    hit_count INT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (cache_key)
);

-- Performance analytics table for adaptive system optimization
CREATE TABLE IF NOT EXISTS adaptive_performance_analytics (
    analytics_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES tech_assessments(assessment_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    attempt_token VARCHAR(100) NOT NULL,
    block_sequence JSONB NOT NULL DEFAULT '[]'::jsonb,
    difficulty_progression JSONB NOT NULL DEFAULT '[]'::jsonb,
    accuracy_progression JSONB NOT NULL DEFAULT '[]'::jsonb,
    time_progression JSONB NOT NULL DEFAULT '[]'::jsonb,
    adaptation_events JSONB DEFAULT '[]'::jsonb,
    final_score DECIMAL(8,2) DEFAULT 0,
    completion_time_seconds INT DEFAULT 0,
    adaptation_success_score DECIMAL(5,4) DEFAULT 0.0000,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_adaptive_blocks_assessment ON adaptive_blocks(assessment_id);
CREATE INDEX IF NOT EXISTS idx_adaptive_blocks_number ON adaptive_blocks(block_number);
CREATE INDEX IF NOT EXISTS idx_block_attempts_token ON block_attempts(attempt_token);
CREATE INDEX IF NOT EXISTS idx_block_attempts_user ON block_attempts(user_id);
CREATE INDEX IF NOT EXISTS idx_block_attempts_status ON block_attempts(status);
CREATE INDEX IF NOT EXISTS idx_adaptive_paths_assessment ON adaptive_paths(assessment_id);
CREATE INDEX IF NOT EXISTS idx_question_pool_assessment ON question_pool_metadata(assessment_id);
CREATE INDEX IF NOT EXISTS idx_question_pool_category ON question_pool_metadata(category, difficulty);
CREATE INDEX IF NOT EXISTS idx_block_cache_key ON block_generation_cache(cache_key);
CREATE INDEX IF NOT EXISTS idx_block_cache_expires ON block_generation_cache(expires_at);
CREATE INDEX IF NOT EXISTS idx_adaptive_analytics_assessment ON adaptive_performance_analytics(assessment_id);
CREATE INDEX IF NOT EXISTS idx_adaptive_analytics_user ON adaptive_performance_analytics(user_id);

-- Add triggers for updating timestamps
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_adaptive_blocks_updated_at BEFORE UPDATE ON adaptive_blocks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_block_attempts_updated_at BEFORE UPDATE ON block_attempts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_adaptive_paths_updated_at BEFORE UPDATE ON adaptive_paths FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_question_pool_metadata_updated_at BEFORE UPDATE ON question_pool_metadata FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Insert default adaptive paths for common assessment types
INSERT INTO adaptive_paths (assessment_id, path_name, path_description, difficulty_progression, category_specialization) 
SELECT 
    a.assessment_id,
    'Standard Progressive',
    'Standard difficulty progression from easy to hard',
    '["easy", "medium", "hard", "hard"]'::jsonb,
    CASE 
        WHEN a.module_type = 'aptitude' THEN '{"QA": 25, "LR": 25, "DI": 25, "AR": 15, "VA": 10}'::jsonb
        WHEN a.module_type = 'grammar' THEN '{"mcq": 40, "reading": 30, "writing": 20, "speaking": 10}'::jsonb
        WHEN a.module_type = 'mnc' THEN '{"Data Structures": 30, "Algorithms": 30, "System Design": 20, "General": 20}'::jsonb
        ELSE '{}'::jsonb
    END
FROM tech_assessments a
WHERE NOT EXISTS (SELECT 1 FROM adaptive_paths WHERE assessment_id = a.assessment_id)
AND a.status = 'active';

INSERT INTO adaptive_paths (assessment_id, path_name, path_description, difficulty_progression, category_specialization) 
SELECT 
    a.assessment_id,
    'Remedial Focus',
    'Focus on easier questions with gradual difficulty increase',
    '["easy", "easy", "medium", "medium"]'::jsonb,
    CASE 
        WHEN a.module_type = 'aptitude' THEN '{"QA": 40, "LR": 30, "DI": 20, "AR": 10}'::jsonb
        WHEN a.module_type = 'grammar' THEN '{"mcq": 60, "reading": 25, "writing": 15}'::jsonb
        WHEN a.module_type = 'mnc' THEN '{"Data Structures": 40, "Algorithms": 35, "General": 25}'::jsonb
        ELSE '{}'::jsonb
    END
FROM tech_assessments a
WHERE NOT EXISTS (
    SELECT 1 FROM adaptive_paths 
    WHERE assessment_id = a.assessment_id AND path_name = 'Remedial Focus'
)
AND a.status = 'active';

INSERT INTO adaptive_paths (assessment_id, path_name, path_description, difficulty_progression, category_specialization) 
SELECT 
    a.assessment_id,
    'Advanced Challenge',
    'Accelerated difficulty progression for high performers',
    '["medium", "hard", "hard", "hard"]'::jsonb,
    CASE 
        WHEN a.module_type = 'aptitude' THEN '{"LR": 30, "DI": 30, "AR": 25, "QA": 15}'::jsonb
        WHEN a.module_type = 'grammar' THEN '{"reading": 35, "writing": 35, "mcq": 20, "speaking": 10}'::jsonb
        WHEN a.module_type = 'mnc' THEN '{"Algorithms": 35, "System Design": 30, "Data Structures": 25, "General": 10}'::jsonb
        ELSE '{}'::jsonb
    END
FROM tech_assessments a
WHERE NOT EXISTS (
    SELECT 1 FROM adaptive_paths 
    WHERE assessment_id = a.assessment_id AND path_name = 'Advanced Challenge'
)
AND a.status = 'active';

-- Create view for adaptive assessment overview
CREATE OR REPLACE VIEW adaptive_assessment_overview AS
SELECT 
    a.assessment_id,
    a.assessment_code,
    a.assessment_name,
    a.module_type,
    a.block_config,
    a.adaptive_config,
    COUNT(ab.block_id) as total_blocks,
    COUNT(CASE WHEN ab.status = 'generated' THEN 1 END) as generated_blocks,
    COUNT(ap.path_id) as available_paths,
    a.status as assessment_status,
    a.created_at
FROM tech_assessments a
LEFT JOIN adaptive_blocks ab ON a.assessment_id = ab.assessment_id
LEFT JOIN adaptive_paths ap ON a.assessment_id = ap.assessment_id AND ap.is_active = true
WHERE (a.block_config->>'enabled')::boolean = true
GROUP BY a.assessment_id, a.assessment_code, a.assessment_name, a.module_type, a.block_config, a.adaptive_config, a.status, a.created_at;
