-- IMPROVED ADAPTIVE SCHEMA - More Advanced Approach

-- 1. Normalized difficulty distributions
CREATE TABLE adaptive_difficulty_distributions (
    distribution_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_number INT NOT NULL,
    easy_weight DECIMAL(5,2) NOT NULL DEFAULT 33.33,
    medium_weight DECIMAL(5,2) NOT NULL DEFAULT 33.33,
    hard_weight DECIMAL(5,2) NOT NULL DEFAULT 33.34,
    total_weight DECIMAL(5,2) GENERATED ALWAYS AS (
        easy_weight + medium_weight + hard_weight
    ) STORED,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 2. Separate question mapping table (better than JSON array)
CREATE TABLE adaptive_block_questions (
    block_question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_id BIGINT NOT NULL REFERENCES adaptive_blocks(block_id) ON DELETE CASCADE,
    question_id BIGINT NOT NULL, -- Reference to actual question table
    question_type VARCHAR(20) NOT NULL, -- 'aptitude', 'grammar', 'mnc', etc.
    sequence_order INT NOT NULL,
    difficulty VARCHAR(10) NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')),
    category VARCHAR(100) NOT NULL,
    points DECIMAL(5,2) NOT NULL DEFAULT 1.0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (block_id, question_id, question_type)
);

-- 3. Enhanced block attempts with more granular tracking
CREATE TABLE enhanced_block_attempts (
    attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_token VARCHAR(100) NOT NULL,
    block_id BIGINT NOT NULL REFERENCES adaptive_blocks(block_id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    block_number INT NOT NULL,
    
    -- Timing analytics
    started_at TIMESTAMP NOT NULL DEFAULT NOW(),
    first_question_at TIMESTAMP,
    last_question_at TIMESTAMP,
    completed_at TIMESTAMP,
    total_time_seconds INT GENERATED ALWAYS AS (
        EXTRACT(EPOCH FROM (completed_at - started_at))
    ) STORED,
    
    -- Performance metrics
    questions_attempted INT NOT NULL DEFAULT 0,
    questions_correct INT NOT NULL DEFAULT 0,
    accuracy_rate DECIMAL(5,4) GENERATED ALWAYS AS (
        CASE 
            WHEN questions_attempted > 0 
            THEN (questions_correct::DECIMAL / questions_attempted::DECIMAL)
            ELSE 0 
        END
    ) STORED,
    
    -- Adaptive metrics
    difficulty_achieved VARCHAR(10) NOT NULL,
    adaptation_score DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
    next_difficulty_recommended VARCHAR(10),
    
    -- Status tracking
    status VARCHAR(20) NOT NULL DEFAULT 'in_progress' 
        CHECK (status IN ('in_progress', 'completed', 'abandoned', 'timeout')),
    
    -- Behavioral analytics
    tab_switches INT DEFAULT 0,
    copy_attempts INT DEFAULT 0,
    idle_time_seconds INT DEFAULT 0,
    
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (attempt_token, block_number)
);

-- 4. Question-level attempt tracking (for detailed analytics)
CREATE TABLE adaptive_question_attempts (
    question_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_attempt_id BIGINT NOT NULL REFERENCES enhanced_block_attempts(attempt_id) ON DELETE CASCADE,
    question_id BIGINT NOT NULL,
    question_type VARCHAR(20) NOT NULL,
    sequence_order INT NOT NULL,
    
    -- Answer tracking
    selected_option_id VARCHAR(50),
    is_correct BOOLEAN NOT NULL DEFAULT FALSE,
    points_earned DECIMAL(5,2) NOT NULL DEFAULT 0.0,
    time_taken_seconds INT NOT NULL DEFAULT 0,
    
    -- Behavioral data
    attempts_count INT NOT NULL DEFAULT 1,
    first_viewed_at TIMESTAMP NOT NULL DEFAULT NOW(),
    answered_at TIMESTAMP,
    review_count INT DEFAULT 0,
    
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (block_attempt_id, question_id, question_type)
);

-- 5. Real-time adaptive analytics (partitioned for performance)
CREATE TABLE adaptive_analytics_partitioned (
    analytics_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    attempt_token VARCHAR(100) NOT NULL,
    
    -- Partition key by date for performance
    analytics_date DATE NOT NULL DEFAULT CURRENT_DATE,
    
    -- Performance summary
    final_score DECIMAL(8,2) NOT NULL DEFAULT 0,
    max_possible_score DECIMAL(8,2) NOT NULL DEFAULT 0,
    score_percentage DECIMAL(5,4) GENERATED ALWAYS AS (
        CASE 
            WHEN max_possible_score > 0 
            THEN (final_score / max_possible_score) * 100
            ELSE 0 
        END
    ) STORED,
    
    completion_time_seconds INT NOT NULL DEFAULT 0,
    average_time_per_question DECIMAL(8,2) GENERATED ALWAYS AS (
        CASE 
            WHEN (SELECT COUNT(*) FROM adaptive_question_attempts qa 
                  JOIN enhanced_block_attempts ba ON qa.block_attempt_id = ba.attempt_id 
                  WHERE ba.attempt_token = adaptive_analytics_partitioned.attempt_token) > 0
            THEN completion_time_seconds::DECIMAL / 
                 (SELECT COUNT(*) FROM adaptive_question_attempts qa 
                  JOIN enhanced_block_attempts ba ON qa.block_attempt_id = ba.attempt_id 
                  WHERE ba.attempt_token = adaptive_analytics_partitioned.attempt_token)
            ELSE 0 
        END
    ) STORED,
    
    -- Adaptive effectiveness
    adaptation_success_score DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
    difficulty_progression_smoothness DECIMAL(5,4) DEFAULT 0.0000,
    prediction_accuracy DECIMAL(5,4) DEFAULT 0.0000,
    
    -- Learning analytics
    weak_areas JSONB DEFAULT '[]'::jsonb,
    strong_areas JSONB DEFAULT '[]'::jsonb,
    improvement_suggestions JSONB DEFAULT '[]'::jsonb,
    
    -- System metrics
    system_performance_score DECIMAL(5,4) DEFAULT 0.0000,
    user_satisfaction_score DECIMAL(5,4) DEFAULT 0.0000,
    
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
) PARTITION BY RANGE (analytics_date);

-- Create monthly partitions
CREATE TABLE adaptive_analytics_y2024m01 PARTITION OF adaptive_analytics_partitioned
    FOR VALUES FROM ('2024-01-01') TO ('2024-02-01');

CREATE TABLE adaptive_analytics_y2024m02 PARTITION OF adaptive_analytics_partitioned
    FOR VALUES FROM ('2024-02-01') TO ('2024-03-01');

-- 6. Advanced caching with TTL
CREATE TABLE adaptive_cache_v2 (
    cache_key VARCHAR(255) PRIMARY KEY,
    cache_data JSONB NOT NULL,
    cache_type VARCHAR(50) NOT NULL, -- 'block_questions', 'difficulty_calc', 'user_profile'
    assessment_id BIGINT,
    user_id BIGINT,
    
    -- TTL management
    expires_at TIMESTAMP NOT NULL,
    hit_count INT DEFAULT 0,
    last_accessed TIMESTAMP NOT NULL DEFAULT NOW(),
    
    -- Cache metadata
    data_size_bytes INT DEFAULT 0,
    generation_time_ms INT DEFAULT 0,
    cache_version INT DEFAULT 1,
    
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 7. Machine learning model storage (for future AI adaptation)
CREATE TABLE adaptive_ml_models (
    model_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR(100) NOT NULL UNIQUE,
    model_type VARCHAR(50) NOT NULL, -- 'difficulty_prediction', 'path_optimization', 'time_estimation'
    model_version VARCHAR(20) NOT NULL,
    
    -- Model storage
    model_data JSONB NOT NULL,
    feature_importance JSONB DEFAULT '{}'::jsonb,
    performance_metrics JSONB DEFAULT '{}'::jsonb,
    
    -- Training data
    training_data_points INT DEFAULT 0,
    last_trained_at TIMESTAMP,
    model_accuracy DECIMAL(5,4) DEFAULT 0.0000,
    
    -- Deployment status
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    deployed_at TIMESTAMP,
    a_b_test_group VARCHAR(20), -- 'control', 'variant_a', 'variant_b'
    
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 8. User adaptive profiles (personalization)
CREATE TABLE adaptive_user_profiles (
    profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) UNIQUE,
    
    -- Learning characteristics
    learning_pace VARCHAR(20) DEFAULT 'moderate', -- 'slow', 'moderate', 'fast'
    difficulty_preference VARCHAR(10) DEFAULT 'adaptive', -- 'easy', 'medium', 'hard', 'adaptive'
    time_pressure_tolerance DECIMAL(5,4) DEFAULT 0.5000, -- 0-1 scale
    
    -- Performance history
    average_accuracy DECIMAL(5,4) DEFAULT 0.0000,
    preferred_categories JSONB DEFAULT '[]'::jsonb,
    weak_categories JSONB DEFAULT '[]'::jsonb,
    
    -- Behavioral patterns
    peak_performance_hours JSONB DEFAULT '[9,10,11,14,15,16]'::jsonb,
    session_length_preference INT DEFAULT 30, -- minutes
    break_frequency INT DEFAULT 3, -- questions between breaks
    
    -- Adaptive settings
    auto_difficulty_adjustment BOOLEAN DEFAULT TRUE,
    personalized_paths BOOLEAN DEFAULT TRUE,
    time_adaptation_enabled BOOLEAN DEFAULT TRUE,
    
    -- Profile analytics
    total_assessments_taken INT DEFAULT 0,
    total_time_spent INT DEFAULT 0, -- seconds
    improvement_rate DECIMAL(5,4) DEFAULT 0.0000,
    
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Enhanced indexes for performance
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_block_questions_block_seq 
ON adaptive_block_questions (block_id, sequence_order);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_question_attempts_block_question 
ON adaptive_question_attempts (block_attempt_id, question_id);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_analytics_date_user 
ON adaptive_analytics_partitioned (analytics_date, user_id);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cache_expires_type 
ON adaptive_cache_v2 (expires_at, cache_type);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_user_profiles_learning 
ON adaptive_user_profiles (learning_pace, difficulty_preference);

-- Advanced triggers for automated analytics
CREATE OR REPLACE FUNCTION update_analytics_trigger()
RETURNS TRIGGER AS $$
BEGIN
    -- Update user profile when block attempt completes
    IF NEW.status = 'completed' AND OLD.status != 'completed' THEN
        UPDATE adaptive_user_profiles 
        SET 
            total_assessments_taken = total_assessments_taken + 1,
            total_time_spent = total_time_spent + NEW.total_time_seconds,
            average_accuracy = (
                SELECT AVG(accuracy_rate) 
                FROM enhanced_block_attempts 
                WHERE user_id = NEW.user_id 
                AND status = 'completed'
            ),
            updated_at = NOW()
        WHERE user_id = NEW.user_id;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_analytics
    AFTER UPDATE ON enhanced_block_attempts
    FOR EACH ROW
    EXECUTE FUNCTION update_analytics_trigger();

-- Automated cache cleanup
CREATE OR REPLACE FUNCTION cleanup_expired_cache()
RETURNS void AS $$
BEGIN
    DELETE FROM adaptive_cache_v2 
    WHERE expires_at < NOW() - INTERVAL '1 hour';
    
    DELETE FROM adaptive_cache_v2 
    WHERE last_accessed < NOW() - INTERVAL '24 hours' 
    AND hit_count < 5;
END;
$$ LANGUAGE plpgsql;

-- Schedule cleanup (requires pg_cron extension)
-- SELECT cron.schedule('cache-cleanup', '0 */6 * * *', 'SELECT cleanup_expired_cache();');

COMMENT ON TABLE adaptive_difficulty_distributions IS 'Normalized difficulty distributions for better data integrity';
COMMENT ON TABLE adaptive_block_questions IS 'Individual question mapping instead of JSON arrays';
COMMENT ON TABLE enhanced_block_attempts IS 'Enhanced block attempts with detailed analytics';
COMMENT ON TABLE adaptive_question_attempts IS 'Question-level tracking for granular insights';
COMMENT ON TABLE adaptive_analytics_partitioned IS 'Partitioned analytics table for better performance';
COMMENT ON TABLE adaptive_cache_v2 IS 'Advanced caching with TTL and metrics';
COMMENT ON TABLE adaptive_ml_models IS 'Storage for machine learning models';
COMMENT ON TABLE adaptive_user_profiles IS 'Personalized user profiles for adaptation';
