-- ============================================================
-- Migration: Full Dynamic Adaptive Block-Based Assessment
-- Idempotent — safe to run multiple times.
-- ============================================================

-- ── 1. tech_assessments extra columns ────────────────────────────────────────
ALTER TABLE tech_assessments
  ADD COLUMN IF NOT EXISTS block_config   JSONB DEFAULT '{"enabled":false,"blocksPerAssessment":0,"questionsPerBlock":5}'::jsonb,
  ADD COLUMN IF NOT EXISTS adaptive_config JSONB DEFAULT '{"enabled":true,"adaptationStrategy":"performance_based"}'::jsonb,
  ADD COLUMN IF NOT EXISTS adaptive_total_questions INT DEFAULT 20;

-- ── 2. Block-tracking columns on aptitude junction ───────────────────────────
ALTER TABLE tech_aptitude_attempt_questions
  ADD COLUMN IF NOT EXISTS block_number         INT NULL,
  ADD COLUMN IF NOT EXISTS block_sequence_order INT NULL;

-- Partial unique index (NULLs allowed for non-block attempts)
DROP INDEX IF EXISTS idx_apt_attempt_questions_block_order;
CREATE UNIQUE INDEX IF NOT EXISTS idx_apt_attempt_questions_block_order
  ON tech_aptitude_attempt_questions (aptitude_attempt_id, block_number, block_sequence_order)
  WHERE block_number IS NOT NULL AND block_sequence_order IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_apt_attempt_questions_block
  ON tech_aptitude_attempt_questions (aptitude_attempt_id, block_number);

-- ── 3. adaptive_blocks ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS adaptive_blocks (
  block_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id           BIGINT  NOT NULL REFERENCES tech_assessments(assessment_id) ON DELETE CASCADE,
  block_number            INT     NOT NULL,
  difficulty_distribution JSONB   NOT NULL DEFAULT '{"easy":60,"medium":30,"hard":10}'::jsonb,
  category_weights        JSONB   DEFAULT '{}'::jsonb,
  time_limit_minutes      INT     DEFAULT NULL,
  is_adaptive             BOOLEAN NOT NULL DEFAULT true,
  adaptation_triggers     JSONB   DEFAULT '{"accuracy_threshold":0.8,"time_threshold":300}'::jsonb,
  generated_questions     JSONB   DEFAULT '[]'::jsonb,   -- array of question IDs assigned
  status                  VARCHAR(20) DEFAULT 'pending'
    CHECK (status IN ('pending','generated','completed','locked')),
  created_at              TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (assessment_id, block_number)
);

-- ── 4. block_attempts ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS block_attempts (
  block_attempt_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_token          VARCHAR(100) NOT NULL,
  block_id               BIGINT NOT NULL REFERENCES adaptive_blocks(block_id) ON DELETE CASCADE,
  user_id                BIGINT NOT NULL REFERENCES users(id),
  block_number           INT    NOT NULL,
  status                 VARCHAR(20) DEFAULT 'not_started'
    CHECK (status IN ('not_started','in_progress','completed','locked')),
  started_at             TIMESTAMP NULL,
  completed_at           TIMESTAMP NULL,
  time_taken_seconds     INT     DEFAULT 0,
  accuracy_score         DECIMAL(5,4) DEFAULT 0.0000,
  correct_count          INT     DEFAULT 0,
  total_count            INT     DEFAULT 0,
  difficulty_achieved    VARCHAR(10) DEFAULT 'easy'
    CHECK (difficulty_achieved IN ('easy','medium','hard')),
  next_block_difficulty  VARCHAR(10) DEFAULT 'medium'
    CHECK (next_block_difficulty IN ('easy','medium','hard')),
  performance_metrics    JSONB   DEFAULT '{}'::jsonb,
  created_at             TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (attempt_token, block_number)
);

-- ── 5. adaptive_paths ────────────────────────────────────────────────────────
-- Stores the difficulty path a user is on for an attempt.
CREATE TABLE IF NOT EXISTS adaptive_paths (
  path_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_token        VARCHAR(100) NOT NULL UNIQUE,
  assessment_id        BIGINT NOT NULL REFERENCES tech_assessments(assessment_id) ON DELETE CASCADE,
  user_id              BIGINT NOT NULL REFERENCES users(id),
  -- JSON array of difficulty per block: ["easy","medium","hard",...]
  difficulty_path      JSONB  NOT NULL DEFAULT '[]'::jsonb,
  -- JSON array of accuracy per block: [0.8, 0.6, ...]
  accuracy_path        JSONB  NOT NULL DEFAULT '[]'::jsonb,
  -- JSON array of time_taken per block (seconds)
  time_path            JSONB  NOT NULL DEFAULT '[]'::jsonb,
  -- Running totals
  total_correct        INT    DEFAULT 0,
  total_questions      INT    DEFAULT 0,
  current_block        INT    DEFAULT 1,
  path_status          VARCHAR(20) DEFAULT 'active'
    CHECK (path_status IN ('active','completed','abandoned')),
  created_at           TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ── 6. adaptive_performance_analytics ────────────────────────────────────────
-- Written once when the full attempt is submitted.
CREATE TABLE IF NOT EXISTS adaptive_performance_analytics (
  analytics_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_token             VARCHAR(100) NOT NULL UNIQUE,
  assessment_id             BIGINT NOT NULL REFERENCES tech_assessments(assessment_id) ON DELETE CASCADE,
  user_id                   BIGINT NOT NULL REFERENCES users(id),
  -- Overall scores
  total_score               DECIMAL(8,2) DEFAULT 0,
  positive_score            DECIMAL(8,2) DEFAULT 0,
  negative_score            DECIMAL(8,2) DEFAULT 0,
  total_questions           INT     DEFAULT 0,
  correct_count             INT     DEFAULT 0,
  accuracy_pct              DECIMAL(5,2) DEFAULT 0,
  time_taken_seconds        INT     DEFAULT 0,
  -- Adaptive journey
  total_blocks_completed    INT     DEFAULT 0,
  difficulty_path           JSONB   DEFAULT '[]'::jsonb,   -- ["easy","medium","hard",...]
  accuracy_path             JSONB   DEFAULT '[]'::jsonb,   -- [0.8, 0.6, ...]
  time_path                 JSONB   DEFAULT '[]'::jsonb,   -- [240, 310, ...]
  block_scores              JSONB   DEFAULT '[]'::jsonb,   -- per-block score breakdown
  -- Weak/strong category analysis
  category_breakdown        JSONB   DEFAULT '{}'::jsonb,
  weak_categories           JSONB   DEFAULT '[]'::jsonb,
  strong_categories         JSONB   DEFAULT '[]'::jsonb,
  -- Adaptation effectiveness
  difficulty_upgrades       INT     DEFAULT 0,
  difficulty_downgrades     INT     DEFAULT 0,
  difficulty_stays          INT     DEFAULT 0,
  adaptation_score          DECIMAL(5,4) DEFAULT 0,        -- 0-1, how well adapted
  created_at                TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ── 7. Indexes ────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_adaptive_blocks_assessment  ON adaptive_blocks(assessment_id);
CREATE INDEX IF NOT EXISTS idx_adaptive_blocks_number      ON adaptive_blocks(block_number);
CREATE INDEX IF NOT EXISTS idx_block_attempts_token        ON block_attempts(attempt_token);
CREATE INDEX IF NOT EXISTS idx_block_attempts_user         ON block_attempts(user_id);
CREATE INDEX IF NOT EXISTS idx_block_attempts_status       ON block_attempts(status);
CREATE INDEX IF NOT EXISTS idx_adaptive_paths_token        ON adaptive_paths(attempt_token);
CREATE INDEX IF NOT EXISTS idx_adaptive_paths_user         ON adaptive_paths(user_id);
CREATE INDEX IF NOT EXISTS idx_adaptive_analytics_token    ON adaptive_performance_analytics(attempt_token);
CREATE INDEX IF NOT EXISTS idx_adaptive_analytics_user     ON adaptive_performance_analytics(user_id);
CREATE INDEX IF NOT EXISTS idx_adaptive_analytics_assess   ON adaptive_performance_analytics(assessment_id);

-- ── 8. updated_at triggers ────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_adaptive_blocks_updated_at') THEN
    CREATE TRIGGER trg_adaptive_blocks_updated_at
      BEFORE UPDATE ON adaptive_blocks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_block_attempts_updated_at') THEN
    CREATE TRIGGER trg_block_attempts_updated_at
      BEFORE UPDATE ON block_attempts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_adaptive_paths_updated_at') THEN
    CREATE TRIGGER trg_adaptive_paths_updated_at
      BEFORE UPDATE ON adaptive_paths FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
END $$;

-- ── Verification ──────────────────────────────────────────────────────────────
-- SELECT table_name FROM information_schema.tables
-- WHERE table_schema='public'
--   AND table_name IN ('adaptive_blocks','block_attempts','adaptive_paths','adaptive_performance_analytics');
