-- Tech assessment module schema: assessments, questions, options, attempts and
-- attempt/question junctions for the aptitude, grammar, mnc and role modules.
--
-- These 17 tables were previously defined only in backend/db/schema.sql, which
-- no migrator ran — it had to be applied by hand. A freshly migrated database
-- was therefore missing the entire tech_* data model, and the services failed
-- against it (tech-assessment-engine swallowed the errors and reported zeros).
-- Folding it in here makes a fresh database complete and keeps the schema in
-- lockstep with the code.
--
-- Every statement is idempotent, so this applies cleanly to existing databases
-- that already have these objects.
--
-- ORDERING: these tables carry foreign keys to users(id), which is created by
-- exam-engine's goose baseline. exam-engine must have migrated the database
-- before assessment-service applies this file. On a shared database that means
-- starting exam-engine first on a fresh install; applying this against a
-- database with no users table fails on the first foreign key.

-- Tech Assessment schema (PostgreSQL)
-- NOTE: This schema assumes an existing users table with users.id.

DO $$
BEGIN
    -- Moved constraint check to after table creation


    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tech_module_type') THEN
        CREATE TYPE tech_module_type AS ENUM ('aptitude', 'grammar', 'coding', 'mnc', 'role');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tech_assessment_status') THEN
        CREATE TYPE tech_assessment_status AS ENUM ('draft', 'active', 'closed');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tech_question_status') THEN
        CREATE TYPE tech_question_status AS ENUM ('active', 'inactive');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tech_difficulty') THEN
        CREATE TYPE tech_difficulty AS ENUM ('easy', 'medium', 'hard');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tech_attempt_status') THEN
        CREATE TYPE tech_attempt_status AS ENUM ('in_progress', 'submitted', 'evaluated', 'expired');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tech_grammar_task_type') THEN
        CREATE TYPE tech_grammar_task_type AS ENUM ('listening_mcq', 'reading_mcq', 'speaking', 'writing');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tech_compile_status') THEN
        CREATE TYPE tech_compile_status AS ENUM ('success', 'compile_error', 'not_run');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tech_run_status') THEN
        CREATE TYPE tech_run_status AS ENUM ('passed', 'failed', 'partial', 'not_run');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tech_role_question_type') THEN
        CREATE TYPE tech_role_question_type AS ENUM ('mcq', 'scenario');
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS tech_assessments (
    assessment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_code VARCHAR(50) NOT NULL UNIQUE,
    assessment_name VARCHAR(150) NOT NULL,
    module_type tech_module_type NOT NULL,
    total_time_minutes INT NOT NULL,
    total_questions INT NOT NULL,
    shuffle_questions BOOLEAN NOT NULL,
    shuffle_options BOOLEAN NOT NULL,
    negative_mark_enabled BOOLEAN NOT NULL,
    negative_mark_value DECIMAL(5,2) NULL,
    status tech_assessment_status NOT NULL,
    amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    trial_question_limit INT NOT NULL DEFAULT 5,
    trial_attempts_limit INT NOT NULL DEFAULT 5,
    main_attempts_limit INT NOT NULL DEFAULT 2,
    email_sending_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    show_certificate_dashboard BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_tech_assessments_negative_mark') THEN
        ALTER TABLE tech_assessments
            ADD CONSTRAINT chk_tech_assessments_negative_mark
            CHECK ((negative_mark_enabled = FALSE AND negative_mark_value IS NULL)
                OR (negative_mark_enabled = TRUE AND negative_mark_value IS NOT NULL));
    END IF;
END $$;


-- TECH Aptitude
CREATE TABLE IF NOT EXISTS tech_aptitude_questions (
    aptitude_question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES tech_assessments(assessment_id),
    subcategory VARCHAR(100) NOT NULL,
    difficulty tech_difficulty NOT NULL,
    question_text TEXT NOT NULL,
    image_url TEXT NULL,
    image_metadata JSON NULL,
    correct_option_id BIGINT NULL,
    marks DECIMAL(5,2) NOT NULL,
    negative_marks DECIMAL(5,2) NOT NULL,
    explanation TEXT NULL,
    status tech_question_status NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tech_aptitude_options (
    option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aptitude_question_id BIGINT NOT NULL REFERENCES tech_aptitude_questions(aptitude_question_id) ON DELETE CASCADE,
    option_text TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tech_aptitude_attempts (
    aptitude_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES tech_assessments(assessment_id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    attempt_token VARCHAR(100) NOT NULL UNIQUE,
    shuffle_seed VARCHAR(100) NOT NULL,
    status tech_attempt_status NOT NULL,
    started_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    submitted_at TIMESTAMP NULL,
    total_score DECIMAL(8,2) NOT NULL DEFAULT 0,
    positive_score DECIMAL(8,2) NOT NULL DEFAULT 0,
    negative_score DECIMAL(8,2) NOT NULL DEFAULT 0,
    time_taken_seconds INT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tech_aptitude_attempt_questions (
    attempt_question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aptitude_attempt_id BIGINT NOT NULL REFERENCES tech_aptitude_attempts(aptitude_attempt_id) ON DELETE CASCADE,
    aptitude_question_id BIGINT NOT NULL REFERENCES tech_aptitude_questions(aptitude_question_id),
    display_order INT NOT NULL,
    block_number INT NULL,
    block_sequence_order INT NULL,
    selected_option_id BIGINT NULL REFERENCES tech_aptitude_options(option_id),
    is_correct BOOLEAN NULL,
    score_awarded DECIMAL(5,2) NOT NULL DEFAULT 0,
    negative_applied DECIMAL(5,2) NOT NULL DEFAULT 0,
    answered_at TIMESTAMP NULL,
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (aptitude_attempt_id, aptitude_question_id),
    UNIQUE (aptitude_attempt_id, block_number, block_sequence_order)
);

CREATE INDEX IF NOT EXISTS idx_apt_attempt_questions_block
    ON tech_aptitude_attempt_questions(aptitude_attempt_id, block_number);

CREATE TABLE IF NOT EXISTS tech_aptitude_attempt_question_options (
    attempt_question_option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_question_id BIGINT NOT NULL REFERENCES tech_aptitude_attempt_questions(attempt_question_id) ON DELETE CASCADE,
    option_id BIGINT NOT NULL REFERENCES tech_aptitude_options(option_id),
    display_order INT NOT NULL,
    UNIQUE (attempt_question_id, option_id),
    UNIQUE (attempt_question_id, display_order)
);

-- TECH Grammar / Communication
CREATE TABLE IF NOT EXISTS tech_grammar_questions (
    grammar_question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES tech_assessments(assessment_id),
    task_type tech_grammar_task_type NOT NULL,
    difficulty tech_difficulty NOT NULL,
    question_text TEXT NOT NULL,
    explanation TEXT NULL,
    audio_url TEXT NULL,
    passage_text TEXT NULL,
    reference_answer TEXT NULL,
    rubric_json JSON NULL,
    correct_option_id BIGINT NULL,
    marks DECIMAL(5,2) NOT NULL,
    negative_marks DECIMAL(5,2) NOT NULL DEFAULT 0,
    status tech_question_status NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tech_grammar_options (
    option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grammar_question_id BIGINT NOT NULL REFERENCES tech_grammar_questions(grammar_question_id) ON DELETE CASCADE,
    option_text TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tech_grammar_attempts (
    grammar_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES tech_assessments(assessment_id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    attempt_token VARCHAR(100) NOT NULL UNIQUE,
    shuffle_seed VARCHAR(100) NOT NULL,
    status tech_attempt_status NOT NULL,
    started_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    submitted_at TIMESTAMP NULL,
    total_score DECIMAL(8,2) NOT NULL DEFAULT 0,
    positive_score DECIMAL(8,2) NOT NULL DEFAULT 0,
    negative_score DECIMAL(8,2) NOT NULL DEFAULT 0,
    time_taken_seconds INT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tech_grammar_attempt_questions (
    attempt_question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grammar_attempt_id BIGINT NOT NULL REFERENCES tech_grammar_attempts(grammar_attempt_id) ON DELETE CASCADE,
    grammar_question_id BIGINT NOT NULL REFERENCES tech_grammar_questions(grammar_question_id),
    display_order INT NOT NULL,
    selected_option_id BIGINT NULL REFERENCES tech_grammar_options(option_id),
    answer_text TEXT NULL,
    answer_audio_url TEXT NULL,
    converted_text TEXT NULL,
    ai_score_json JSON NULL,
    is_correct BOOLEAN NULL,
    score_awarded DECIMAL(5,2) NOT NULL DEFAULT 0,
    negative_applied DECIMAL(5,2) NOT NULL DEFAULT 0,
    answered_at TIMESTAMP NULL,
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (grammar_attempt_id, grammar_question_id)
);

CREATE TABLE IF NOT EXISTS tech_grammar_attempt_question_options (
    attempt_question_option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_question_id BIGINT NOT NULL REFERENCES tech_grammar_attempt_questions(attempt_question_id) ON DELETE CASCADE,
    option_id BIGINT NOT NULL REFERENCES tech_grammar_options(option_id),
    display_order INT NOT NULL,
    UNIQUE (attempt_question_id, option_id),
    UNIQUE (attempt_question_id, display_order)
);

-- TECH Coding
CREATE TABLE IF NOT EXISTS tech_coding_questions (
    coding_question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES tech_assessments(assessment_id),
    difficulty tech_difficulty NOT NULL,
    problem_title VARCHAR(150) NOT NULL,
    problem_statement TEXT NOT NULL,
    input_format TEXT NULL,
    output_format TEXT NULL,
    constraints TEXT NULL,
    starter_code TEXT NULL,
    starter_code_json JSON NULL,
    starter_files_json JSON NULL,
    entry_file_json JSON NULL,
    limits_json JSON NULL,
    sample_io_json JSON NULL,
    hidden_testcases_ref TEXT NULL,
    allowed_languages_json JSON NULL,
    marks DECIMAL(5,2) NOT NULL,
    negative_marks DECIMAL(5,2) NOT NULL DEFAULT 0,
    status tech_question_status NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tech_coding_attempts (
    coding_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES tech_assessments(assessment_id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    attempt_token VARCHAR(100) NOT NULL UNIQUE,
    status tech_attempt_status NOT NULL,
    started_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    submitted_at TIMESTAMP NULL,
    total_score DECIMAL(8,2) NOT NULL DEFAULT 0,
    positive_score DECIMAL(8,2) NOT NULL DEFAULT 0,
    negative_score DECIMAL(8,2) NOT NULL DEFAULT 0,
    time_taken_seconds INT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tech_coding_attempt_questions (
    attempt_question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coding_attempt_id BIGINT NOT NULL REFERENCES tech_coding_attempts(coding_attempt_id) ON DELETE CASCADE,
    coding_question_id BIGINT NOT NULL REFERENCES tech_coding_questions(coding_question_id),
    display_order INT NOT NULL,
    language VARCHAR(50) NULL,
    submitted_code TEXT NULL,
    judge_input_ref TEXT NULL,
    judge_output_ref TEXT NULL,
    compile_status tech_compile_status NULL,
    run_status tech_run_status NULL,
    judge_result_json JSON NULL,
    is_correct BOOLEAN NULL,
    score_awarded DECIMAL(5,2) NOT NULL DEFAULT 0,
    negative_applied DECIMAL(5,2) NOT NULL DEFAULT 0,
    execution_time_ms INT NULL,
    memory_used_kb INT NULL,
    submitted_at TIMESTAMP NULL,
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (coding_attempt_id, coding_question_id)
);

-- TECH MNC-Based DSA
CREATE TABLE IF NOT EXISTS tech_mnc_questions (
    mnc_question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES tech_assessments(assessment_id),
    topic_group VARCHAR(100) NOT NULL,
    category VARCHAR(100) NULL,
    subcategory VARCHAR(100) NULL,
    difficulty tech_difficulty NOT NULL,
    question_text TEXT NOT NULL,
    explanation TEXT NULL,
    correct_option_id BIGINT NULL,
    marks DECIMAL(5,2) NOT NULL,
    negative_marks DECIMAL(5,2) NOT NULL,
    status tech_question_status NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tech_mnc_options (
    option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mnc_question_id BIGINT NOT NULL REFERENCES tech_mnc_questions(mnc_question_id) ON DELETE CASCADE,
    option_text TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tech_mnc_attempts (
    mnc_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES tech_assessments(assessment_id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    attempt_token VARCHAR(100) NOT NULL UNIQUE,
    shuffle_seed VARCHAR(100) NOT NULL,
    status tech_attempt_status NOT NULL,
    started_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    submitted_at TIMESTAMP NULL,
    total_score DECIMAL(8,2) NOT NULL DEFAULT 0,
    positive_score DECIMAL(8,2) NOT NULL DEFAULT 0,
    negative_score DECIMAL(8,2) NOT NULL DEFAULT 0,
    time_taken_seconds INT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tech_mnc_attempt_questions (
    attempt_question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mnc_attempt_id BIGINT NOT NULL REFERENCES tech_mnc_attempts(mnc_attempt_id) ON DELETE CASCADE,
    mnc_question_id BIGINT NOT NULL REFERENCES tech_mnc_questions(mnc_question_id),
    display_order INT NOT NULL,
    selected_option_id BIGINT NULL REFERENCES tech_mnc_options(option_id),
    is_correct BOOLEAN NULL,
    score_awarded DECIMAL(5,2) NOT NULL DEFAULT 0,
    negative_applied DECIMAL(5,2) NOT NULL DEFAULT 0,
    answered_at TIMESTAMP NULL,
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (mnc_attempt_id, mnc_question_id)
);

CREATE TABLE IF NOT EXISTS tech_mnc_attempt_question_options (
    attempt_question_option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_question_id BIGINT NOT NULL REFERENCES tech_mnc_attempt_questions(attempt_question_id) ON DELETE CASCADE,
    option_id BIGINT NOT NULL REFERENCES tech_mnc_options(option_id),
    display_order INT NOT NULL,
    UNIQUE (attempt_question_id, option_id),
    UNIQUE (attempt_question_id, display_order)
);

-- TECH Role-Based
CREATE TABLE IF NOT EXISTS tech_role_questions (
    role_question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES tech_assessments(assessment_id),
    domain VARCHAR(100) NOT NULL,
    difficulty VARCHAR(10) NOT NULL DEFAULT 'medium',
    category VARCHAR(100) NULL,
    subcategory VARCHAR(100) NULL,
    question_type tech_role_question_type NOT NULL,
    question_text TEXT NOT NULL,
    explanation TEXT NULL,
    scenario_context TEXT NULL,
    metadata JSONB NULL,
    image_url TEXT NULL,
    correct_option_id BIGINT NULL,
    marks DECIMAL(5,2) NOT NULL,
    negative_marks DECIMAL(5,2) NOT NULL,
    status tech_question_status NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tech_role_options (
    option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_question_id BIGINT NOT NULL REFERENCES tech_role_questions(role_question_id) ON DELETE CASCADE,
    option_text TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tech_role_attempts (
    role_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES tech_assessments(assessment_id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    attempt_token VARCHAR(100) NOT NULL UNIQUE,
    shuffle_seed VARCHAR(100) NOT NULL,
    status tech_attempt_status NOT NULL,
    started_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    submitted_at TIMESTAMP NULL,
    total_score DECIMAL(8,2) NOT NULL DEFAULT 0,
    positive_score DECIMAL(8,2) NOT NULL DEFAULT 0,
    negative_score DECIMAL(8,2) NOT NULL DEFAULT 0,
    time_taken_seconds INT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tech_role_attempt_questions (
    attempt_question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_attempt_id BIGINT NOT NULL REFERENCES tech_role_attempts(role_attempt_id) ON DELETE CASCADE,
    role_question_id BIGINT NOT NULL REFERENCES tech_role_questions(role_question_id),
    display_order INT NOT NULL,
    block_number INT NULL,
    block_sequence_order INT NULL,
    selected_option_id BIGINT NULL REFERENCES tech_role_options(option_id),
    is_correct BOOLEAN NULL,
    score_awarded DECIMAL(5,2) NOT NULL DEFAULT 0,
    negative_applied DECIMAL(5,2) NOT NULL DEFAULT 0,
    answered_at TIMESTAMP NULL,
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    expected_time_seconds INT NULL,
    time_taken_seconds INT NOT NULL DEFAULT 0,
    metadata JSONB NULL,
    UNIQUE (role_attempt_id, role_question_id)
);

CREATE TABLE IF NOT EXISTS tech_role_attempt_question_options (
    attempt_question_option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_question_id BIGINT NOT NULL REFERENCES tech_role_attempt_questions(attempt_question_id) ON DELETE CASCADE,
    option_id BIGINT NOT NULL REFERENCES tech_role_options(option_id),
    display_order INT NOT NULL,
    UNIQUE (attempt_question_id, option_id),
    UNIQUE (attempt_question_id, display_order)
);

-- Add FK constraints for correct_option_id after options tables exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_aptitude_correct_option') THEN
        ALTER TABLE tech_aptitude_questions
            ADD CONSTRAINT fk_aptitude_correct_option
            FOREIGN KEY (correct_option_id) REFERENCES tech_aptitude_options(option_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_grammar_correct_option') THEN
        ALTER TABLE tech_grammar_questions
            ADD CONSTRAINT fk_grammar_correct_option
            FOREIGN KEY (correct_option_id) REFERENCES tech_grammar_options(option_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_mnc_correct_option') THEN
        ALTER TABLE tech_mnc_questions
            ADD CONSTRAINT fk_mnc_correct_option
            FOREIGN KEY (correct_option_id) REFERENCES tech_mnc_options(option_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_role_correct_option') THEN
        ALTER TABLE tech_role_questions
            ADD CONSTRAINT fk_role_correct_option
            FOREIGN KEY (correct_option_id) REFERENCES tech_role_options(option_id);
    END IF;
END $$;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_tech_assessments_module ON tech_assessments(module_type);
CREATE INDEX IF NOT EXISTS idx_aptitude_questions_assessment ON tech_aptitude_questions(assessment_id);
CREATE INDEX IF NOT EXISTS idx_grammar_questions_assessment ON tech_grammar_questions(assessment_id);
CREATE INDEX IF NOT EXISTS idx_coding_questions_assessment ON tech_coding_questions(assessment_id);
CREATE INDEX IF NOT EXISTS idx_mnc_questions_assessment ON tech_mnc_questions(assessment_id);
CREATE INDEX IF NOT EXISTS idx_role_questions_assessment ON tech_role_questions(assessment_id);
CREATE INDEX IF NOT EXISTS idx_aptitude_attempts_assessment ON tech_aptitude_attempts(assessment_id);
CREATE INDEX IF NOT EXISTS idx_aptitude_attempts_user ON tech_aptitude_attempts(user_id);
CREATE INDEX IF NOT EXISTS idx_grammar_attempts_assessment ON tech_grammar_attempts(assessment_id);
CREATE INDEX IF NOT EXISTS idx_grammar_attempts_user ON tech_grammar_attempts(user_id);
CREATE INDEX IF NOT EXISTS idx_coding_attempts_assessment ON tech_coding_attempts(assessment_id);
CREATE INDEX IF NOT EXISTS idx_coding_attempts_user ON tech_coding_attempts(user_id);
CREATE INDEX IF NOT EXISTS idx_mnc_attempts_assessment ON tech_mnc_attempts(assessment_id);
CREATE INDEX IF NOT EXISTS idx_mnc_attempts_user ON tech_mnc_attempts(user_id);
CREATE INDEX IF NOT EXISTS idx_role_attempts_assessment ON tech_role_attempts(assessment_id);
CREATE INDEX IF NOT EXISTS idx_role_attempts_user ON tech_role_attempts(user_id);

-- TECH Assessment Purchases
-- assessment_id is NULLABLE: coding-language purchases live in the Go
-- exam-engine's pricing_items table and have no row in tech_assessments,
-- but we still record the payment audit row here.
CREATE TABLE IF NOT EXISTS tech_assessment_purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    user_id BIGINT NULL REFERENCES users(id),
    assessment_id BIGINT NULL REFERENCES tech_assessments(assessment_id),
    assessment_code VARCHAR(100) NOT NULL,
    amount DECIMAL(10,2) NOT NULL DEFAULT 0,
    razorpay_order_id VARCHAR(150) NULL,
    razorpay_payment_id VARCHAR(150) NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    purchased_at TIMESTAMP NOT NULL DEFAULT NOW(),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Idempotently relax the constraint on databases that pre-date the change.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'tech_assessment_purchases'
          AND column_name = 'assessment_id'
          AND is_nullable = 'NO'
    ) THEN
        EXECUTE 'ALTER TABLE tech_assessment_purchases ALTER COLUMN assessment_id DROP NOT NULL';
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_tech_assessment_purchases_email
    ON tech_assessment_purchases(LOWER(email));

CREATE INDEX IF NOT EXISTS idx_tech_assessment_purchases_user
    ON tech_assessment_purchases(user_id);

CREATE INDEX IF NOT EXISTS idx_tech_assessment_purchases_assessment
    ON tech_assessment_purchases(assessment_id);

-- Add explanation column to other question tables if they don't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'tech_grammar_questions' AND column_name = 'explanation'
    ) THEN
        ALTER TABLE tech_grammar_questions ADD COLUMN explanation TEXT NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'tech_mnc_questions' AND column_name = 'explanation'
    ) THEN
        ALTER TABLE tech_mnc_questions ADD COLUMN explanation TEXT NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'tech_role_questions' AND column_name = 'explanation'
    ) THEN
        ALTER TABLE tech_role_questions ADD COLUMN explanation TEXT NULL;
    END IF;
END $$;

-- Add mode column to the module question tables if it doesn't exist.
-- The services filter every question query by mode ('main' = graded run,
-- 'trial' = practice run); see ModuleConfigs in tech-assessment-engine and
-- the attempts-stats split. Defaults to 'main' so pre-existing rows stay
-- visible to the graded flow.
DO $$
DECLARE
    tbl TEXT;
BEGIN
    FOREACH tbl IN ARRAY ARRAY[
        'tech_aptitude_questions',
        'tech_grammar_questions',
        'tech_mnc_questions',
        'tech_role_questions'
    ] LOOP
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = tbl AND column_name = 'mode'
        ) THEN
            EXECUTE format(
                'ALTER TABLE %I ADD COLUMN mode VARCHAR(16) NOT NULL DEFAULT ''main''',
                tbl
            );
            EXECUTE format(
                'ALTER TABLE %I ADD CONSTRAINT %I CHECK (mode IN (''main'', ''trial''))',
                tbl, tbl || '_mode_check'
            );
            EXECUTE format(
                'CREATE INDEX IF NOT EXISTS %I ON %I(assessment_id, status, mode)',
                'idx_' || tbl || '_mode', tbl
            );
        END IF;
    END LOOP;
END $$;

-- Add the shared category/subcategory pair the services select on every
-- module question query (getAttemptQuestionsByConfig). Only the columns
-- genuinely absent are added; the rest already ship above.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'tech_aptitude_questions' AND column_name = 'category'
    ) THEN
        ALTER TABLE tech_aptitude_questions ADD COLUMN category VARCHAR(120) NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'tech_grammar_questions' AND column_name = 'category'
    ) THEN
        ALTER TABLE tech_grammar_questions ADD COLUMN category VARCHAR(120) NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'tech_grammar_questions' AND column_name = 'subcategory'
    ) THEN
        ALTER TABLE tech_grammar_questions ADD COLUMN subcategory VARCHAR(120) NULL;
    END IF;
END $$;

-- tech_assessments.categories: jsonb list of category weights read back during
-- submission scoring (see TechAssessment.Categories / the submit query's
-- assessment_categories alias).
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'tech_assessments' AND column_name = 'categories'
    ) THEN
        ALTER TABLE tech_assessments ADD COLUMN categories JSONB NULL;
    END IF;
END $$;

-- Add mode to the module ATTEMPT tables.
--
-- assessment-service records which run an attempt belongs to and reads it back
-- (`SELECT mode FROM <attempts> WHERE attempt_token = ...`), and its attempt
-- inserts name the column explicitly. Some call sites guard with a runtime
-- column-existence check and some do not, so a database without this column
-- fails on starting an attempt.
DO $$
DECLARE
    tbl TEXT;
BEGIN
    FOREACH tbl IN ARRAY ARRAY[
        'tech_aptitude_attempts',
        'tech_grammar_attempts',
        'tech_mnc_attempts',
        'tech_role_attempts'
    ] LOOP
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = tbl AND column_name = 'mode'
        ) THEN
            EXECUTE format(
                'ALTER TABLE %I ADD COLUMN mode VARCHAR(16) NOT NULL DEFAULT ''main''',
                tbl
            );
            EXECUTE format(
                'ALTER TABLE %I ADD CONSTRAINT %I CHECK (mode IN (''main'', ''trial''))',
                tbl, tbl || '_mode_check'
            );
            EXECUTE format(
                'CREATE INDEX IF NOT EXISTS %I ON %I(user_id, mode, status)',
                'idx_' || tbl || '_user_mode', tbl
            );
        END IF;
    END LOOP;
END $$;

-- Remaining JSONB configuration columns the services read.
--
-- tech_assessments carries per-assessment configuration that both
-- assessment-service and exam-engine select by name: block/adaptive settings,
-- which question kinds are enabled, and per-difficulty negative marking. The
-- question tables carry a free-form metadata blob whose `kind` key selects the
-- MCQ variant (mcq / msq / tf / numerical).
--
-- All are nullable with sensible defaults so existing rows keep their current
-- behaviour: no block mode, no adaptive mode, all question kinds enabled.
DO $$
DECLARE
    tbl TEXT;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'tech_assessments' AND column_name = 'block_config') THEN
        ALTER TABLE tech_assessments ADD COLUMN block_config JSONB NOT NULL DEFAULT '{}'::jsonb;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'tech_assessments' AND column_name = 'adaptive_config') THEN
        ALTER TABLE tech_assessments ADD COLUMN adaptive_config JSONB NOT NULL DEFAULT '{}'::jsonb;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'tech_assessments' AND column_name = 'enabled_question_types') THEN
        ALTER TABLE tech_assessments ADD COLUMN enabled_question_types JSONB NOT NULL DEFAULT '{}'::jsonb;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'tech_assessments' AND column_name = 'difficulty_negative_marks') THEN
        ALTER TABLE tech_assessments ADD COLUMN difficulty_negative_marks JSONB NULL;
    END IF;

    FOREACH tbl IN ARRAY ARRAY[
        'tech_aptitude_questions',
        'tech_grammar_questions',
        'tech_mnc_questions',
        'tech_role_questions'
    ] LOOP
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = tbl AND column_name = 'metadata'
        ) THEN
            EXECUTE format(
                'ALTER TABLE %I ADD COLUMN metadata JSONB NOT NULL DEFAULT ''{}''::jsonb',
                tbl
            );
        END IF;
    END LOOP;
END $$;

-- Per-answer metadata on the attempt/question junctions.
--
-- assessment-service stores the submitted answer payload here (selected
-- option(s), free text, audio reference) and selects it back as
-- `attempt_metadata` when resuming or reviewing an attempt.
DO $$
DECLARE
    tbl TEXT;
BEGIN
    FOREACH tbl IN ARRAY ARRAY[
        'tech_aptitude_attempt_questions',
        'tech_grammar_attempt_questions',
        'tech_mnc_attempt_questions',
        'tech_role_attempt_questions'
    ] LOOP
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = tbl AND column_name = 'metadata'
        ) THEN
            EXECUTE format(
                'ALTER TABLE %I ADD COLUMN metadata JSONB NOT NULL DEFAULT ''{}''::jsonb',
                tbl
            );
        END IF;
    END LOOP;
END $$;
